// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL_jH6-Oh60enA4JOAZKatkkGIXNJ2dkk',
    appId: '1:211171371696:web:6274838125e52a63706975',
    messagingSenderId: '211171371696',
    projectId: 'wow-encuestas',
    authDomain: 'wow-encuestas.firebaseapp.com',
    storageBucket: 'wow-encuestas.firebasestorage.app',
    measurementId: 'G-D9BMWHZ0VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4O152_h0e3biyf0jJpc5noXA2a3CMxOI',
    appId: '1:211171371696:android:8f269f670627e5ad706975',
    messagingSenderId: '211171371696',
    projectId: 'wow-encuestas',
    storageBucket: 'wow-encuestas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYKVLmoCyFjutprKD8m4v80GslpodU5Ic',
    appId: '1:211171371696:ios:2c4eeaddd397a382706975',
    messagingSenderId: '211171371696',
    projectId: 'wow-encuestas',
    storageBucket: 'wow-encuestas.firebasestorage.app',
    iosBundleId: 'com.example.appEncuestas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYKVLmoCyFjutprKD8m4v80GslpodU5Ic',
    appId: '1:211171371696:ios:2c4eeaddd397a382706975',
    messagingSenderId: '211171371696',
    projectId: 'wow-encuestas',
    storageBucket: 'wow-encuestas.firebasestorage.app',
    iosBundleId: 'com.example.appEncuestas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL_jH6-Oh60enA4JOAZKatkkGIXNJ2dkk',
    appId: '1:211171371696:web:944ebbcb9d3801e9706975',
    messagingSenderId: '211171371696',
    projectId: 'wow-encuestas',
    authDomain: 'wow-encuestas.firebaseapp.com',
    storageBucket: 'wow-encuestas.firebasestorage.app',
    measurementId: 'G-WNM60KK7JB',
  );
}
